version: "3.7"
networks:
        reverse:
                name: reverse_proxy_net
services:
        reverse_proxy:
                hostname: reverse_proxy
                build:
                        context: .
                        dockerfile: ./docker/nginx/Dockerfile
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - ./html:/usr/share/nginx/html:ro
                        - ./docker/nginx/ssl:/etc/ssl/private
                        - ./docker/nginx/nginx_etc:/etc/nginx
                networks:
                        - reverse
                        - default
