version: "3.3"
services:
  webserver:
    build:
            #context: .
            dockerfile: ./docker/nginx/Dockerfile
            #image: "nginx:1.21.3-alpine"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html:ro
